#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { lstat, readFile, readdir } from 'node:fs/promises';
import { dirname, isAbsolute, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
const here=dirname(fileURLToPath(import.meta.url));const root=resolve(here,'..');const manifestPath=resolve(here,'manifest.v1.json');
const fail=m=>{console.error(`[conformance] ${m}`);process.exitCode=1;};
const safe=(v,l)=>{if(typeof v!=='string'||!v||isAbsolute(v))throw new Error(`${l} must be repository-relative`);const r=resolve(root,v),rel=relative(root,r);if(rel==='..'||rel.startsWith(`..${sep}`)||isAbsolute(rel))throw new Error(`${l} escapes repository root: ${v}`);return r;};
const files=async p=>{const start=safe(p,'root'),s=await lstat(start);if(s.isSymbolicLink()||!s.isDirectory())throw new Error(`invalid authority root: ${p}`);const out=[];const walk=async d=>{const es=await readdir(d,{withFileTypes:true});es.sort((a,b)=>a.name.localeCompare(b.name));for(const e of es){const f=resolve(d,e.name),st=await lstat(f),rel=relative(root,f).split(sep).join('/');if(st.isSymbolicLink())throw new Error(`symlink forbidden: ${rel}`);if(st.isDirectory())await walk(f);else if(st.isFile())out.push({f,rel});}};await walk(start);return out;};
const digest=async xs=>{const h=createHash('sha256');for(const x of[...xs].sort((a,b)=>a.rel.localeCompare(b.rel))){h.update(x.rel);h.update(Buffer.from([0]));h.update(await readFile(x.f));h.update(Buffer.from([0]));}return h.digest('hex');};
try{const m=JSON.parse(await readFile(manifestPath,'utf8'));if(m.schema!=='ores.conformance.manifest/v1')throw new Error('invalid manifest schema');if(!['bootstrap','enforced'].includes(m.coverageStatus))throw new Error('coverageStatus must be bootstrap or enforced');if(!Array.isArray(m.contractRoots)||!m.contractRoots.length||!Array.isArray(m.caseRoots)||!m.caseRoots.length||!Array.isArray(m.requiredParticipants))throw new Error('invalid manifest roots/participants');const c=(await Promise.all(m.contractRoots.map(files))).flat(),k=(await Promise.all(m.caseRoots.map(files))).flat();if(!k.length)throw new Error('conformance corpus is empty');const ids=new Set();for(const x of k){if(!x.rel.endsWith('.json'))throw new Error(`case roots may contain only JSON: ${x.rel}`);const v=JSON.parse(await readFile(x.f,'utf8'));if(!v||Array.isArray(v)||typeof v!=='object'||typeof v.schema!=='string'||!v.schema||typeof v.id!=='string'||!v.id)throw new Error(`case requires schema and id: ${x.rel}`);const id=`${v.schema}\u0000${v.id}`;if(ids.has(id))throw new Error(`duplicate case identity ${v.schema}:${v.id}`);ids.add(id);}const contractsSha256=await digest(c),corpusSha256=await digest(k),pids=new Set();for(const p of m.requiredParticipants){if(!p||typeof p.id!=='string'||!p.id||pids.has(p.id))throw new Error('participant ids must be unique non-empty strings');pids.add(p.id);}if(m.coverageStatus==='enforced'){if(!m.requiredParticipants.length)throw new Error('enforced coverage requires participants');const ed=safe(m.evidenceDir,'evidenceDir');for(const p of m.requiredParticipants){const e=JSON.parse(await readFile(resolve(ed,`${p.id}.json`),'utf8'));if(e.schema!=='ores.conformance.evidence/v1'||e.participant!==p.id||e.contractsSha256!==contractsSha256||e.corpusSha256!==corpusSha256)throw new Error(`invalid or stale evidence for ${p.id}`);}}console.log(JSON.stringify({schema:'ores.conformance.check/v1',coverageStatus:m.coverageStatus,contractFileCount:c.length,caseFileCount:k.length,contractsSha256,corpusSha256,requiredParticipants:m.requiredParticipants.map(({id})=>id)},null,2));}catch(e){fail(e instanceof Error?e.message:String(e));}
